// Synthesized game audio via WebAudio — no asset files.
// AudioContext unlocks on the first user gesture (browser autoplay policy).

const GEARS = [0, 14, 26, 40, 58, 78, 100]; // speed breakpoints → fake gear shifts

export class AudioEngine {
  constructor() {
    this.ctx = null;
    this.rev = 0;
    this.muted = localStorage.getItem('dc-muted') === '1';
    this.wantMusic = null;
    this.musicKind = null;
    fetch(`${import.meta.env.BASE_URL}music/playlist.json`)
      .then((r) => r.json())
      .then((p) => { this.playlist = p; this._syncMusic(); })
      .catch(() => { this.playlist = null; });
    const unlock = () => {
      if (!this.ctx) this.setup();
      if (this.ctx.state === 'suspended') this.ctx.resume().then(() => this._syncMusic());
      this._syncMusic();
    };
    // 'click' (not pointerdown!) — Chrome only counts a completed click as
    // user activation for audio, so unlocking on pointerdown logs a warning.
    addEventListener('click', unlock);
    addEventListener('keydown', (e) => {
      unlock();
      // not while typing a name/room code — an 'M' there must not mute the game
      if (e.code === 'KeyM' && !/^(INPUT|TEXTAREA)$/.test(e.target.tagName)) this.toggleMute();
    });
  }

  setup() {
    const ctx = new AudioContext();
    this.ctx = ctx;
    this.master = ctx.createGain();
    this.master.gain.value = this.muted ? 0 : 0.5;
    const limiter = ctx.createDynamicsCompressor();
    limiter.threshold.value = -10;
    limiter.knee.value = 6;
    limiter.ratio.value = 8;
    limiter.attack.value = 0.002;
    limiter.release.value = 0.12;
    this.master.connect(limiter);
    limiter.connect(ctx.destination);

    // Shared white-noise buffer (screech, intake, impact debris).
    const noiseBuf = ctx.createBuffer(1, ctx.sampleRate, ctx.sampleRate);
    const data = noiseBuf.getChannelData(0);
    for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
    this.noiseBuf = noiseBuf;

    // Engine voice. Layers that make it read as "car" instead of "synth":
    //  - sub square at half the note (the exhaust burble / odd-fire thrum)
    //  - main saw + a 2x harmonic saw (the body of the note)
    //  - intake noise that swells with throttle
    // all crushed through a soft-clip waveshaper, then a lowpass whose cutoff
    // opens with revs and throttle (closed = muffled cruise, open = growl).
    this.engGain = ctx.createGain();
    this.engGain.gain.value = 0;

    const shaper = ctx.createWaveShaper();
    const curve = new Float32Array(257);
    for (let i = 0; i < 257; i++) {
      const x = (i / 128) - 1;
      curve[i] = Math.tanh(2.8 * x);
    }
    shaper.curve = curve;
    shaper.oversample = '2x';

    this.engFilter = ctx.createBiquadFilter();
    this.engFilter.type = 'lowpass';
    this.engFilter.frequency.value = 500;
    this.engFilter.Q.value = 1.1;

    shaper.connect(this.engFilter);
    this.engFilter.connect(this.engGain);
    this.engGain.connect(this.master);

    const layer = (type, gainVal) => {
      const osc = ctx.createOscillator();
      osc.type = type;
      osc.frequency.value = 40;
      const g = ctx.createGain();
      g.gain.value = gainVal;
      osc.connect(g);
      g.connect(shaper);
      osc.start();
      return osc;
    };
    this.engSub = layer('square', 0.5);    // f/2 burble
    this.engMain = layer('sawtooth', 0.45);
    this.engHarm = layer('sawtooth', 0.25); // 2f
    this.engHarm.detune.value = 6;

    // Intake/exhaust hiss, swells with throttle.
    const intake = ctx.createBufferSource();
    intake.buffer = noiseBuf;
    intake.loop = true;
    const intakeFilter = ctx.createBiquadFilter();
    intakeFilter.type = 'lowpass';
    intakeFilter.frequency.value = 480;
    this.intakeGain = ctx.createGain();
    this.intakeGain.gain.value = 0;
    intake.connect(intakeFilter);
    intakeFilter.connect(this.intakeGain);
    this.intakeGain.connect(shaper);
    intake.start();

    // Skid loop: a pre-rendered tire-squeal SAMPLE (public/sfx/skid.wav,
    // generated by scripts/gen-skid-sample.mjs). Pitch rides slip angle via
    // playbackRate — sample playback is how real racing games do this.
    this.skidGain = ctx.createGain();
    this.skidGain.gain.value = 0;
    this.skidGain.connect(this.master);
    this.skidRate = 1;
    fetch(`${import.meta.env.BASE_URL}sfx/skid.wav`)
      .then((r) => r.arrayBuffer())
      .then((ab) => ctx.decodeAudioData(ab))
      .then((buf) => {
        const src2 = ctx.createBufferSource();
        src2.buffer = buf;
        src2.loop = true;
        src2.connect(this.skidGain);
        src2.start();
        this.skidSource = src2;
      })
      .catch(() => { /* no sample — drift falls back to the scrub bed */ });

    // Scrub: the main drift voice now — mid-band rubber grind with slow
    // chatter tremolo (tires juddering over the surface).
    const scrub = ctx.createBufferSource();
    scrub.buffer = noiseBuf;
    scrub.loop = true;
    this.scrubFilter = ctx.createBiquadFilter();
    this.scrubFilter.type = 'bandpass';
    this.scrubFilter.frequency.value = 300;
    this.scrubFilter.Q.value = 0.5; // wide & deep — rumble, not honk
    this.scrubGain = ctx.createGain();
    this.scrubGain.gain.value = 0;
    const chatter = ctx.createGain();
    chatter.gain.value = 1;
    for (const [rate, depth] of [[7.3, 0.16], [2.9, 0.1]]) {
      const lfo = ctx.createOscillator();
      lfo.frequency.value = rate;
      const lg = ctx.createGain();
      lg.gain.value = depth;
      lfo.connect(lg);
      lg.connect(chatter.gain);
      lfo.start();
    }
    scrub.connect(this.scrubFilter);
    this.scrubFilter.connect(this.scrubGain);
    this.scrubGain.connect(chatter);
    chatter.connect(this.master);
    scrub.start(0, 0.5); // offset so the two noise loops don't correlate

  }

  // ---- music: user-supplied files in public/music/ (see README there) ----
  playMusic(kind) { // 'menu' | 'race' | null
    this.wantMusic = kind;
    this._syncMusic();
  }

  _syncMusic() {
    if (!this.ctx || this.ctx.state !== 'running' || !this.playlist) return;
    const kind = this.wantMusic;
    if (kind === this.musicKind) return;
    clearTimeout(this.musicTimer);
    this._fadeOutMusic();
    this.musicKind = kind;
    if (kind && (this.playlist[kind] ?? []).length) this._playTrack(kind);
  }

  // Rotation per kind: first play starts at a random track, then every song
  // end (and every re-entry into the kind) advances to the next, cycling.
  _nextTrack(kind) {
    const list = this.playlist[kind];
    this.musicIdx ??= {};
    const cur = this.musicIdx[kind];
    this.musicIdx[kind] = cur == null ? Math.floor(Math.random() * list.length) : (cur + 1) % list.length;
    return list[this.musicIdx[kind]];
  }

  _playTrack(kind) {
    const list = this.playlist[kind];
    const el = new Audio(`${import.meta.env.BASE_URL}music/` + this._nextTrack(kind));
    el.loop = list.length === 1; // a one-track playlist just loops
    const srcNode = this.ctx.createMediaElementSource(el);
    const g = this.ctx.createGain();
    g.gain.value = 0;
    srcNode.connect(g);
    g.connect(this.master);
    el.play()
      .then(() => g.gain.setTargetAtTime(0.35, this.ctx.currentTime, 0.6))
      .catch(() => { /* file missing or blocked — stay silent */ });
    el.onended = () => {
      if (this.wantMusic !== kind) return;
      // quiet cooldown between tracks (playlist.json: raceCooldown /
      // menuCooldown seconds), long for races, short in the menu.
      const cooldown = (this.playlist[kind + 'Cooldown'] ?? (kind === 'race' ? 8 : 3)) * 1000;
      this.musicTimer = setTimeout(() => {
        if (this.wantMusic === kind) this._playTrack(kind);
      }, cooldown);
    };
    el.onerror = () => { if (this.music?.el === el) this.music = null; };
    // keep srcNode referenced — an unreferenced element can be GC'd mid-play
    this.music = { el, g, srcNode };
  }

  _fadeOutMusic() {
    if (!this.music) return;
    const { el, g } = this.music;
    el.onended = el.onerror = null; // src='' below fires 'error' on this dead element
    g.gain.setTargetAtTime(0, this.ctx.currentTime, 0.25);
    setTimeout(() => { el.pause(); el.src = ''; }, 900);
    this.music = null;
  }

  toggleMute() {
    this.muted = !this.muted;
    localStorage.setItem('dc-muted', this.muted ? '1' : '0');
    if (this.master) this.master.gain.value = this.muted ? 0 : 0.5;
  }

  // Called every frame with the local car's state.
  update(dt, { speed, throttle, slip, drifting, active, grounded = true }) {
    if (!this.ctx || this.ctx.state !== 'running') return;
    const t = this.ctx.currentTime;

    if (!active) {
      this.engGain.gain.setTargetAtTime(0, t, 0.2);
      this.intakeGain.gain.setTargetAtTime(0, t, 0.2);
      this.skidGain.gain.setTargetAtTime(0, t, 0.1);
      this.scrubGain.gain.setTargetAtTime(0, t, 0.1);
      return;
    }

    // Fake gearbox: RPM climbs within the gear band, drops on shift.
    let gear = 0;
    while (gear < GEARS.length - 2 && speed > GEARS[gear + 1]) gear++;
    const band = (speed - GEARS[gear]) / (GEARS[gear + 1] - GEARS[gear]);
    const rpm = Math.min(Math.max(band, 0), 1);

    // Rev state: on the ground it tracks the gearbox; in the air the wheels
    // are unloaded, so throttle FREE-REVS toward the limiter and lifting
    // lets it fall — then it snaps back to road speed on landing.
    const revTarget = grounded ? rpm : (Math.abs(throttle) > 0.1 ? 1 : 0.3);
    const revRate = grounded ? 16 : (revTarget > this.rev ? 3.5 : 2.2);
    this.rev += (revTarget - this.rev) * Math.min(1, revRate * dt);

    // Exhaust-note fundamental, ~32 Hz idle to ~140 Hz on the limiter, with a
    // slow wobble so idle/cruise doesn't sound like a held synth note.
    const wobble = 1 + (0.010 * Math.sin(t * 9.3) + 0.006 * Math.sin(t * 27.1)) * (1 - this.rev * 0.6);
    const f = (32 + gear * 8 + this.rev * 78) * wobble;
    this.engMain.frequency.setTargetAtTime(f, t, 0.035);
    this.engSub.frequency.setTargetAtTime(f / 2, t, 0.035);
    this.engHarm.frequency.setTargetAtTime(f * 2, t, 0.035);

    // Filter opens with revs + throttle: muffled cruise, growl under load —
    // airborne free-rev opens it fully (that zingy unloaded scream).
    const filt = grounded
      ? 260 + this.rev * 1500 + Math.abs(throttle) * 550
      : 500 + this.rev * 2100;
    this.engFilter.frequency.setTargetAtTime(filt, t, 0.07);
    const load = grounded
      ? 0.1 + Math.abs(throttle) * 0.13 + this.rev * 0.08
      : 0.08 + this.rev * 0.12;
    this.engGain.gain.setTargetAtTime(load, t, 0.08);
    this.intakeGain.gain.setTargetAtTime(Math.abs(throttle) * 0.16, t, 0.1);

    // Drift voice with real DYNAMICS: light slides whisper, deep fast drifts
    // roar. drive ~ slip^1.4 scaled by speed — the drift-game swell.
    const slipAmt = Math.min(Math.abs(slip) / 14, 1);
    const drive = drifting
      ? Math.pow(slipAmt, 1.4) * (0.45 + Math.min(speed / 90, 1) * 0.55)
      : 0;
    this.scrubGain.gain.setTargetAtTime(drive * 0.03, t, 0.08);
    this.scrubFilter.frequency.setTargetAtTime(260 + slipAmt * 180 + speed * 1.2, t, 0.1);
    // The star: the recorded-style skid loop, pitched by slip angle.
    this.skidGain.gain.setTargetAtTime(drive * 0.3, t, 0.05);
    if (this.skidSource) {
      const rate = 0.8 + slipAmt * 0.45 + Math.min(speed / 100, 1) * 0.15;
      this.skidSource.playbackRate.setTargetAtTime(rate, t, 0.07);
    }
  }

  // Impact: low thump + debris noise, plus a voice per kind — metallic clang
  // off walls, a duller crunch between cars, nothing extra for landings.
  impact(strength, kind = 'wall') {
    if (!this.ctx || this.ctx.state !== 'running') return;
    const amt = Math.min(strength / 25, 1);
    if (amt < 0.08) return;
    const t = this.ctx.currentTime;
    // Rate limit: a sustained wall grind fires every frame — without this it
    // spawns hundreds of nodes/sec and chokes the audio thread.
    if (t - (this._impactAt ?? -1) < 0.1) return;
    this._impactAt = t;

    const thump = this.ctx.createOscillator();
    thump.type = 'sine';
    thump.frequency.setValueAtTime(kind === 'car' ? 95 : 120, t);
    thump.frequency.exponentialRampToValueAtTime(38, t + 0.15);
    const tg = this.ctx.createGain();
    tg.gain.setValueAtTime(0.5 * amt, t);
    tg.gain.exponentialRampToValueAtTime(0.001, t + 0.18);
    thump.connect(tg); tg.connect(this.master);
    thump.start(t); thump.stop(t + 0.2);

    const noise = this.ctx.createBufferSource();
    noise.buffer = this.noiseBuf;
    const nf = this.ctx.createBiquadFilter();
    nf.type = kind === 'car' ? 'lowpass' : 'highpass';
    nf.frequency.value = kind === 'car' ? 500 : 900;
    const ng = this.ctx.createGain();
    ng.gain.setValueAtTime((kind === 'car' ? 0.32 : 0.25) * amt, t);
    ng.gain.exponentialRampToValueAtTime(0.001, t + (kind === 'car' ? 0.2 : 0.12));
    noise.connect(nf); nf.connect(ng); ng.connect(this.master);
    noise.start(t, Math.random()); noise.stop(t + 0.25);

    if (kind === 'wall' && amt > 0.25) {
      // Metallic ring: two detuned partials through a resonant bandpass.
      const f0 = 420 + Math.random() * 380;
      for (const [ratio, g0] of [[1, 0.22], [2.76, 0.1]]) {
        const osc = this.ctx.createOscillator();
        osc.type = 'square';
        osc.frequency.value = f0 * ratio;
        const bp = this.ctx.createBiquadFilter();
        bp.type = 'bandpass';
        bp.frequency.value = f0 * ratio;
        bp.Q.value = 9;
        const g = this.ctx.createGain();
        g.gain.setValueAtTime(g0 * amt, t);
        g.gain.exponentialRampToValueAtTime(0.001, t + 0.22);
        osc.connect(bp); bp.connect(g); g.connect(this.master);
        osc.start(t); osc.stop(t + 0.25);
      }
    }
  }

  beep(freq, dur = 0.12, vol = 0.25, type = 'square') {
    if (!this.ctx || this.ctx.state !== 'running') return;
    const t = this.ctx.currentTime;
    const osc = this.ctx.createOscillator();
    osc.type = type;
    osc.frequency.value = freq;
    const g = this.ctx.createGain();
    g.gain.setValueAtTime(vol, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + dur);
    osc.connect(g); g.connect(this.master);
    osc.start(t); osc.stop(t + dur + 0.02);
  }

  // Lightweight positional engine for OTHER cars: saw + half-order square
  // through a lowpass into a 3D panner. Pitch tracks their speed; the panner
  // handles left/right placement and distance falloff automatically.
  carVoice() {
    if (!this.ctx || this.ctx.state !== 'running') return null;
    const ctx = this.ctx;
    const filter = ctx.createBiquadFilter();
    filter.type = 'lowpass';
    filter.frequency.value = 600;
    const gain = ctx.createGain();
    gain.gain.value = 0;
    const pan = ctx.createPanner();
    pan.panningModel = 'equalpower';
    pan.distanceModel = 'inverse';
    pan.refDistance = 16;
    pan.rolloffFactor = 1.4;
    pan.maxDistance = 700;
    const oscs = [];
    for (const [type, mult, g0] of [['sawtooth', 1, 0.5], ['square', 0.5, 0.38]]) {
      const o = ctx.createOscillator();
      o.type = type;
      o.frequency.value = 45 * mult;
      o.detune.value = (Math.random() - 0.5) * 18; // each car slightly different
      const g = ctx.createGain();
      g.gain.value = g0;
      o.connect(g); g.connect(filter);
      o.start();
      oscs.push({ o, mult });
    }
    filter.connect(gain); gain.connect(pan); pan.connect(this.master);
    return {
      update: (x, y, z, speed) => {
        const t = ctx.currentTime;
        const f = 34 + (speed / 100) * 95;
        for (const { o, mult } of oscs) o.frequency.setTargetAtTime(f * mult, t, 0.06);
        filter.frequency.setTargetAtTime(360 + speed * 6, t, 0.1);
        gain.gain.setTargetAtTime(0.34, t, 0.15);
        if (pan.positionX) {
          pan.positionX.setTargetAtTime(x, t, 0.03);
          pan.positionY.setTargetAtTime(y, t, 0.03);
          pan.positionZ.setTargetAtTime(z, t, 0.03);
        } else {
          pan.setPosition(x, y, z);
        }
      },
      dispose: () => {
        for (const { o } of oscs) { try { o.stop(); } catch { /* already stopped */ } }
        pan.disconnect();
      },
    };
  }

  // Listener = the local car, facing camera-forward, so "left" is screen-left.
  updateListener(x, y, z, fx, fz) {
    if (!this.ctx || this.ctx.state !== 'running') return;
    const l = this.ctx.listener;
    const t = this.ctx.currentTime;
    if (l.positionX) {
      l.positionX.setTargetAtTime(x, t, 0.03);
      l.positionY.setTargetAtTime(y, t, 0.03);
      l.positionZ.setTargetAtTime(z, t, 0.03);
      l.forwardX.setTargetAtTime(fx, t, 0.05);
      l.forwardY.value = 0;
      l.forwardZ.setTargetAtTime(fz, t, 0.05);
      l.upX.value = 0; l.upY.value = 1; l.upZ.value = 0;
    } else {
      l.setPosition(x, y, z);
      l.setOrientation(fx, 0, fz, 0, 1, 0);
    }
  }

  countTick() { this.beep(440, 0.14, 0.22); }

  // Rising zip for the drift exit boost.
  boost() {
    if (!this.ctx || this.ctx.state !== 'running') return;
    const t = this.ctx.currentTime;
    const osc = this.ctx.createOscillator();
    osc.type = 'sawtooth';
    osc.frequency.setValueAtTime(280, t);
    osc.frequency.exponentialRampToValueAtTime(980, t + 0.28);
    const g = this.ctx.createGain();
    g.gain.setValueAtTime(0.16, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + 0.32);
    osc.connect(g); g.connect(this.master);
    osc.start(t); osc.stop(t + 0.35);
  }
  go() { this.beep(880, 0.4, 0.28); }
  lap() { this.beep(1320, 0.1, 0.15, 'sine'); }

  finish() {
    if (!this.ctx || this.ctx.state !== 'running') return;
    [660, 880, 1100, 1320].forEach((f, i) => {
      setTimeout(() => this.beep(f, 0.18, 0.22, 'triangle'), i * 130);
    });
  }
}
